### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by glcamila** [YUCHEN005/DPSL-ASR#3]
![6 8](https://github.com/YUCHEN005/DPSL-ASR/assets/101648474/7e31d532-9dce-4b88-94b3-878cb8f3429e)

请问这个报错怎么解决呢？尝试过调大stack size到12288，没能解决。

**Comment by YUCHEN005** [comment]
你这是在哪个step报的错？我查了一下drive上的data，他是用espnet处理出来的fbank特征，检查了下应该没啥毛病。这个bug还有可能是环境版本的问题，我的是torch 1.4.0 python 3.7.10 espnet 0.9.6。
